import Foundation

extension PeekabooBridgeOperation {
    /// TCC permissions an operation relies on. Used to gate advertisement/handling.
    public var requiredPermissions: Set<PeekabooBridgePermissionKind> {
        switch self {
        case .captureScreen, .captureWindow, .captureFrontmost, .captureArea, .detectElements,
             .desktopObservation:
            [.screenRecording]
        case .targetedHotkey, .targetedTypeActions:
            [.postEvent]
        case .inspectAccessibilityTree,
             .click, .type, .typeActions, .setValue, .performAction, .scroll, .hotkey, .swipe, .drag, .moveMouse,
             .waitForElement, .listWindows, .focusWindow, .moveWindow, .resizeWindow, .setWindowBounds, .closeWindow,
             .minimizeWindow, .maximizeWindow, .getFocusedWindow, .listMenus, .listFrontmostMenus,
             .clickMenuItem, .clickMenuItemByName, .listMenuExtras, .clickMenuExtra, .menuExtraOpenMenuFrame,
             .listMenuBarItems, .clickMenuBarItemNamed, .clickMenuBarItemIndex, .listDockItems, .launchDockItem,
             .rightClickDockItem, .hideDock, .showDock, .isDockHidden, .findDockItem, .dialogFindActive,
             .dialogClickButton, .dialogEnterText, .dialogHandleFile, .dialogDismiss, .dialogListElements:
            [.accessibility]
        case ._appleScriptProbe,
             .permissionsStatus,
             .requestPostEventPermission,
             .daemonStatus,
             .daemonStop,
             .browserStatus,
             .browserConnect,
             .browserDisconnect,
             .browserExecute,
             .createSnapshot,
             .storeDetectionResult,
             .getDetectionResult,
             .storeScreenshot,
             .storeAnnotatedScreenshot,
             .listSnapshots,
             .getMostRecentSnapshot,
             .invalidateImplicitLatestSnapshot,
             .cleanSnapshot,
             .cleanSnapshotsOlderThan,
             .cleanAllSnapshots,
             .listApplications,
             .findApplication,
             .getFrontmostApplication,
             .isApplicationRunning,
             .launchApplication,
             .launchApplicationWithOptions,
             .relaunchApplicationWithOptions,
             .activateApplication,
             .quitApplication,
             .hideApplication,
             .unhideApplication,
             .hideOtherApplications,
             .showAllApplications,
             .targetedClick,
             .exactWindowTargetedClick:
            []
        }
    }

    /// Operations enabled by default for remote helper hosts.
    public static let remoteDefaultAllowlist: Set<PeekabooBridgeOperation> = [
        .permissionsStatus,
        .requestPostEventPermission,
        .daemonStatus,
        .daemonStop,
        .browserStatus,
        .browserConnect,
        .browserDisconnect,
        .browserExecute,
        .captureScreen,
        .captureWindow,
        .captureFrontmost,
        .captureArea,
        .detectElements,
        .inspectAccessibilityTree,
        .desktopObservation,
        .click,
        .type,
        .typeActions,
        .setValue,
        .performAction,
        .scroll,
        .hotkey,
        .targetedHotkey,
        .targetedTypeActions,
        .targetedClick,
        .exactWindowTargetedClick,
        .swipe,
        .drag,
        .moveMouse,
        .waitForElement,
        .listWindows,
        .focusWindow,
        .moveWindow,
        .resizeWindow,
        .setWindowBounds,
        .closeWindow,
        .minimizeWindow,
        .maximizeWindow,
        .getFocusedWindow,
        .listApplications,
        .findApplication,
        .getFrontmostApplication,
        .isApplicationRunning,
        .launchApplication,
        .launchApplicationWithOptions,
        .relaunchApplicationWithOptions,
        .activateApplication,
        .quitApplication,
        .hideApplication,
        .unhideApplication,
        .hideOtherApplications,
        .showAllApplications,
        .listMenus,
        .listFrontmostMenus,
        .clickMenuItem,
        .clickMenuItemByName,
        .listMenuExtras,
        .clickMenuExtra,
        .menuExtraOpenMenuFrame,
        .listMenuBarItems,
        .clickMenuBarItemNamed,
        .clickMenuBarItemIndex,
        .listDockItems,
        .launchDockItem,
        .rightClickDockItem,
        .hideDock,
        .showDock,
        .isDockHidden,
        .findDockItem,
        .dialogFindActive,
        .dialogClickButton,
        .dialogEnterText,
        .dialogHandleFile,
        .dialogDismiss,
        .dialogListElements,
        .createSnapshot,
        .storeDetectionResult,
        .getDetectionResult,
        .storeScreenshot,
        .storeAnnotatedScreenshot,
        .listSnapshots,
        .getMostRecentSnapshot,
        .invalidateImplicitLatestSnapshot,
        .cleanSnapshot,
        .cleanSnapshotsOlderThan,
        .cleanAllSnapshots,
        ._appleScriptProbe,
    ]
}
